/**
 * @file HeaderSynthesizer.cpp
 * @brief Mode 3: C/C++ Struct Header Synthesizer Engine (!structscan emit)
 */

#include "../include/structscan.h"
#include <cwchar>

static std::wstring SanitizeStructName(const wchar_t* target) {
    std::wstring structName = L"RECONSTRUCTED_";
    for (size_t i = 0; target[i] != L'\0'; i++) {
        wchar_t c = target[i];
        structName += (iswalnum(c) ? c : L'_');
    }
    return structName;
}

static const wchar_t* GetFieldCType(FieldType type) {
    static constexpr const wchar_t* kCTypes[] = {
        L"uint64_t         ", // Unknown
        L"PVOID            ", // Pointer
        L"LIST_ENTRY       ", // ListEntry
        L"UNICODE_STRING   ", // UnicodeString
        L"char             ", // AsciiString
        L"ULONG            ", // PoolTag
        L"uint64_t         ", // Integer
        L"uint64_t         ", // Flags
        L"HANDLE           ", // Handle
        L"uint8_t          ", // Padding
    };
    auto idx = static_cast<size_t>(type);
    return (idx < sizeof(kCTypes) / sizeof(kCTypes[0])) ? kCTypes[idx] : L"uint64_t         ";
}

static std::wstring ExtractPointerSymbolName(const std::wstring& annotation) {
    if (annotation.empty()) return L"";
    const wchar_t* bang = wcschr(annotation.c_str(), L'!');
    const wchar_t* symStart = bang ? (bang + 1) : annotation.c_str();
    std::wstring sName;
    for (size_t k = 0; symStart[k] != L'\0'; k++) {
        wchar_t c = symStart[k];
        if (iswalnum(c) || c == L'_') sName += c;
        else break;
    }
    return (sName == L"string") ? L"" : sName;
}

static void EmitPaddingField(IDebugControl4* ctrl, ULONG offset, ULONG length) {
    if (length == 0) return;
    wchar_t padLine[256] = {};
    swprintf_s(padLine, L"    /* +0x%04lx */ uint8_t           Padding_%04lx[%lu];\n",
        offset, offset, static_cast<unsigned long>(length));
    ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS, L"%s", padLine);
}

static void EmitStructMember(IDebugControl4* ctrl, const FieldAnalysis& fa) {
    const wchar_t* cType = GetFieldCType(fa.type);
    std::wstring fName;

    if (fa.type == FieldType::Pointer) {
        fName = ExtractPointerSymbolName(fa.annotation);
    }

    if (fName.empty()) {
        wchar_t fn[64] = {};
        swprintf_s(fn, L"Field_%04lx", fa.offset);
        fName = fn;
    }

    if (fa.type == FieldType::AsciiString) {
        fName += L"[" + std::to_wstring(fa.size > 0 ? fa.size : 8) + L"]";
    }

    std::wstring comment = fa.annotation.empty() ? L"" : (L" // " + fa.annotation);

    wchar_t fieldLine[512] = {};
    swprintf_s(fieldLine, L"    /* +0x%04lx */ %s %-24s;%s\n",
        fa.offset, cType, fName.c_str(), comment.c_str());
    ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS, L"%s", fieldLine);
}

HRESULT DoEmitHeader(
    const DebugContext& ctx,
    const wchar_t*      target,
    ULONG               scanWindow
) {
    ULONG64 addr = ResolveTarget(ctx.sym, target, nullptr);
    if (addr == 0) {
        ctx.ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS, L"[-] Cannot resolve: %s\n", target);
        return E_FAIL;
    }

    std::vector<uint8_t> buf(scanWindow);
    ULONG rd = 0;
    if (FAILED(ctx.ds->ReadVirtual(addr, buf.data(), scanWindow, &rd)) || rd == 0) return E_FAIL;

    SmartFieldAnalyzer analyzer;
    analyzer.DataSpaces = ctx.ds;
    analyzer.Symbols    = ctx.sym;

    std::vector<FieldAnalysis> fields;
    for (ULONG off = 0; off + 8 <= rd; ) {
        auto fa = analyzer.Analyze(buf.data(), rd, off, addr);
        if (fa.type != FieldType::Unknown && fa.type != FieldType::Padding && fa.confidence > 0.25) {
            fields.push_back(fa);
        }
        off += (fa.size > 0) ? fa.size : 8;
    }

    std::wstring structName = SanitizeStructName(target);

    ctx.ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS,
        L"// Auto-generated by StructScan v4.0 (AI Structure Synthesizer)\n"
        L"// Target: %s (0x%016llx) | Scan Window: 0x%lx bytes\n\n",
        target, static_cast<unsigned long long>(addr), static_cast<unsigned long>(rd));

    ctx.ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS,
        L"typedef struct _%s {\n", structName.c_str());

    ULONG currentOffset = 0;
    for (const auto& fa : fields) {
        if (fa.offset > currentOffset) {
            EmitPaddingField(ctx.ctrl, currentOffset, fa.offset - currentOffset);
            currentOffset = fa.offset;
        }
        EmitStructMember(ctx.ctrl, fa);
        currentOffset = fa.offset + fa.size;
    }

    if (currentOffset < rd) {
        EmitPaddingField(ctx.ctrl, currentOffset, rd - currentOffset);
    }

    ctx.ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS,
        L"} %s, *P%s;\n\n", structName.c_str(), structName.c_str());

    return S_OK;
}
