/**
 * @file HeaderSynthesizer.cpp
 * @brief Mode 3: C/C++ Struct Header Synthesizer Engine (!structscan emit)
 */

#include "../include/structscan.h"
#include <cwchar>

HRESULT DoEmitHeader(
    IDebugControl4*    ctrl,
    IDebugSymbols4*    sym,
    IDebugDataSpaces4* ds,
    const wchar_t*     target,
    ULONG              scanWindow
) {
    ULONG64 addr = ResolveTarget(ctrl, sym, target, nullptr, nullptr, 0, nullptr);
    if (addr == 0) {
        ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS, L"[-] Cannot resolve: %s\n", target);
        return E_FAIL;
    }

    std::vector<uint8_t> buf(scanWindow);
    ULONG rd = 0;
    if (FAILED(ds->ReadVirtual(addr, buf.data(), scanWindow, &rd)) || rd == 0) return E_FAIL;

    SmartFieldAnalyzer analyzer;
    analyzer.DataSpaces = ds;
    analyzer.Symbols    = sym;

    std::vector<FieldAnalysis> fields;
    for (ULONG off = 0; off + 8 <= rd; off += 8) {
        auto fa = analyzer.Analyze(buf.data(), rd, off, addr);
        if (fa.type != FieldType::Unknown && fa.type != FieldType::Padding && fa.confidence > 0.25) {
            fields.push_back(fa);
        }
    }

    std::wstring structName = L"RECONSTRUCTED_";
    for (size_t i = 0; i < wcslen(target); i++) {
        wchar_t c = target[i];
        if (iswalnum(c)) structName += c;
        else structName += L'_';
    }

    ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS,
        L"// Auto-generated by StructScan v4.0 (AI Structure Synthesizer)\n"
        L"// Target: %s (0x%016llx) | Scan Window: 0x%lx bytes\n\n",
        target, static_cast<unsigned long long>(addr), static_cast<unsigned long>(rd));

    ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS,
        L"typedef struct _%s {\n", structName.c_str());

    ULONG currentOffset = 0;

    for (size_t i = 0; i < fields.size(); i++) {
        const auto& fa = fields[i];

        if (fa.offset > currentOffset) {
            ULONG padLen = fa.offset - currentOffset;
            wchar_t padLine[256] = {};
            swprintf_s(padLine, L"    /* +0x%04lx */ uint8_t           Padding_%04lx[%lu];\n",
                currentOffset, currentOffset, static_cast<unsigned long>(padLen));
            ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS, L"%s", padLine);
            currentOffset = fa.offset;
        }

        wchar_t fieldLine[512] = {};
        const wchar_t* cType = L"uint64_t         ";
        std::wstring fName;

        switch (fa.type) {
            case FieldType::Pointer:
                cType = L"PVOID            ";
                if (!fa.annotation.empty()) {
                    std::wstring sName;
                    const wchar_t* bang = wcschr(fa.annotation.c_str(), L'!');
                    const wchar_t* symStart = bang ? (bang + 1) : fa.annotation.c_str();
                    for (size_t k = 0; symStart[k] != L'\0'; k++) {
                        wchar_t c = symStart[k];
                        if (iswalnum(c) || c == L'_') sName += c;
                        else break;
                    }
                    if (!sName.empty() && sName != L"string") fName = sName;
                }
                break;
            case FieldType::ListEntry:
                cType = L"LIST_ENTRY       ";
                break;
            case FieldType::UnicodeString:
                cType = L"UNICODE_STRING   ";
                break;
            case FieldType::AsciiString:
                cType = L"char             ";
                break;
            case FieldType::PoolTag:
                cType = L"ULONG            ";
                break;
            case FieldType::Handle:
                cType = L"HANDLE           ";
                break;
            case FieldType::Flags:
                cType = L"uint64_t         ";
                break;
            case FieldType::Integer:
                cType = L"uint64_t         ";
                break;
            default:
                cType = L"uint64_t         ";
                break;
        }

        if (fName.empty()) {
            wchar_t fn[64] = {};
            swprintf_s(fn, L"Field_%04lx", fa.offset);
            fName = fn;
        }

        std::wstring comment;
        if (!fa.annotation.empty()) {
            comment = L" // " + fa.annotation;
        }

        swprintf_s(fieldLine, L"    /* +0x%04lx */ %s %-24s%s\n",
            fa.offset, cType, fName.c_str(), comment.c_str());
        ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS, L"%s", fieldLine);

        ULONG size = 8;
        if (fa.type == FieldType::UnicodeString || fa.type == FieldType::ListEntry) size = 16;
        currentOffset = fa.offset + size;
    }

    if (currentOffset < rd) {
        ULONG padLen = rd - currentOffset;
        wchar_t padLine[256] = {};
        swprintf_s(padLine, L"    /* +0x%04lx */ uint8_t           Padding_%04lx[%lu];\n",
            currentOffset, currentOffset, static_cast<unsigned long>(padLen));
        ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS, L"%s", padLine);
    }

    ctrl->OutputWide(DEBUG_OUTCTL_ALL_CLIENTS,
        L"} %s, *P%s;\n\n", structName.c_str(), structName.c_str());

    return S_OK;
}
